name: 🐛 Bug Report
description: Report a bug or unexpected behavior in DOFTool
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.
        
        **⚠️ Security Issues**: If this is a security vulnerability, please **DO NOT** open a public issue. Instead, report it via [Security Advisories](https://github.com/asterixix/DOFTool/security/advisories/new) or email artur@sendyka.dev.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of DOFTool
          required: true
        - label: This is not a security vulnerability (those should be reported privately)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which part of DOFTool is affected?
      multiple: true
      options:
        - Calendar
        - Tasks
        - Email
        - Family/Sync
        - Settings
        - Encryption/Security
        - UI/UX
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DOFTool Version
      description: Which version of DOFTool are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running DOFTool on?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - Ubuntu 22.04+
        - Fedora 38+
        - Other Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Please paste any relevant logs or error messages. This will be automatically formatted as code.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., network conditions, number of family members, email provider).
