name: 📚 Documentation Improvement
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs help everyone use DOFTool effectively.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Typo/grammar issue
        - Missing code examples
        - Broken links
        - Translation improvement
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which document or section needs improvement?
      placeholder: "e.g., README.md, docs/ARCHITECTURE.md, or 'Installation section'"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: Quote or describe the current documentation that needs improvement.
      placeholder: Paste the current text or describe what's there (or missing)...

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What changes would you like to see?
      placeholder: Describe how the documentation should be improved...
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR with this documentation improvement

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context that would help us improve the documentation.
