/**
 * Crash Reporting Service - GitHub Issues URL generation
 *
 * Opens a pre-filled GitHub issue template in the default browser
 * This approach doesn't require GitHub tokens and lets users review before submitting
 */

interface ErrorDetails {
  message: string;
  stack?: string | undefined;
  filename?: string | undefined;
  lineno?: number | undefined;
  colno?: number | undefined;
  userAgent?: string | undefined;
  url?: string | undefined;
  timestamp: number;
}

/**
 * Create GitHub issue URL with pre-filled template
 */
function createGitHubIssueUrl(error: ErrorDetails): string {
  const GITHUB_OWNER = 'asterixix';
  const GITHUB_REPO = 'DOFTool';
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
  const appVersion: string =
    (import.meta as unknown as { env: { VITE_APP_VERSION?: string } }).env.VITE_APP_VERSION ??
    '0.1.0';

  const title = `[Crash] ${error.message.substring(0, 100)}`.replace(/\n/g, ' ');

  const body = `## Crash Report

### Error Message
\`\`\`
${error.message}
\`\`\`

### Stack Trace
\`\`\`
${error.stack ?? 'No stack trace available'}
\`\`\`

### Environment
- **Timestamp**: ${new Date(error.timestamp).toISOString()}
- **User Agent**: ${error.userAgent ?? 'Unknown'}
- **URL**: ${error.url ?? 'Unknown'}
- **Filename**: ${error.filename ?? 'Unknown'}
- **Line**: ${error.lineno ?? 'Unknown'}
- **Column**: ${error.colno ?? 'Unknown'}

### App Information
- **Version**: ${appVersion}
- **Platform**: ${typeof window !== 'undefined' ? window.navigator.platform : 'Unknown'}

---
*This issue template was automatically generated by DOFTool crash reporting.*`;

  // URL encode the title and body
  const encodedTitle = encodeURIComponent(title);
  const encodedBody = encodeURIComponent(body);
  const labels = encodeURIComponent('crash-report,auto-generated');

  return `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/new?title=${encodedTitle}&body=${encodedBody}&labels=${labels}`;
}

/**
 * Open crash report in GitHub Issues (pre-filled template)
 */
async function openGitHubIssue(error: ErrorDetails): Promise<void> {
  // Check if electronAPI is available
  if (!window.electronAPI?.openExternal) {
    console.warn('[CrashReporting] ElectronAPI not available, cannot open GitHub issue');
    // Fallback: try opening in current window
    const url = createGitHubIssueUrl(error);
    window.open(url, '_blank');
    return;
  }

  try {
    const url = createGitHubIssueUrl(error);
    const result = await window.electronAPI.openExternal(url);
    if (result.success) {
      // eslint-disable-next-line no-console
      console.log('[CrashReporting] Opened GitHub issue template in browser');
    } else {
      console.warn('[CrashReporting] Failed to open GitHub issue:', result.error);
    }
  } catch (error) {
    console.error('[CrashReporting] Failed to open GitHub issue:', error);
    // Don't throw - we don't want crash reporting failures to crash the app
  }
}

/**
 * Check if crash reporting is enabled
 */
function isCrashReportingEnabled(): boolean {
  try {
    // Use dynamic import to avoid circular dependency
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const settingsModule = require('@/stores/settings.store') as {
      useSettingsStore: {
        getState: () => { privacy: { crashReportsEnabled: boolean } };
      };
    };
    const state = settingsModule.useSettingsStore.getState();
    return state.privacy.crashReportsEnabled;
  } catch {
    return false;
  }
}

/**
 * Report a crash/error
 */
export async function reportCrash(error: ErrorDetails): Promise<void> {
  if (!isCrashReportingEnabled()) {
    // eslint-disable-next-line no-console
    console.log('[CrashReporting] Disabled by user preference');
    return;
  }

  // Debounce reports to avoid spam (max 1 per minute)
  const lastReportKey = 'crash-report-last-time';
  const lastReportTime = localStorage.getItem(lastReportKey);
  const now = Date.now();

  if (lastReportTime && now - parseInt(lastReportTime, 10) < 60000) {
    // eslint-disable-next-line no-console
    console.log('[CrashReporting] Rate limited - skipping duplicate report');
    return;
  }

  localStorage.setItem(lastReportKey, now.toString());

  // Clean up old rate limit after 5 minutes
  setTimeout(() => {
    localStorage.removeItem(lastReportKey);
  }, 300000);

  await openGitHubIssue(error);
}

/**
 * Create error details from Error object
 */
export function createErrorDetails(
  error: Error | ErrorEvent | PromiseRejectionEvent,
  additionalInfo?: {
    filename?: string;
    lineno?: number;
    colno?: number;
  }
): ErrorDetails {
  const details: ErrorDetails = {
    message: '',
    timestamp: Date.now(),
  };

  // Set optional properties explicitly (handling exactOptionalPropertyTypes)
  const userAgent = typeof window !== 'undefined' ? window.navigator.userAgent : undefined;
  if (userAgent !== undefined) {
    details.userAgent = userAgent;
  }

  const url = typeof window !== 'undefined' ? window.location.href : undefined;
  if (url !== undefined) {
    details.url = url;
  }

  if (additionalInfo?.filename !== undefined) {
    details.filename = additionalInfo.filename;
  }
  if (additionalInfo?.lineno !== undefined) {
    details.lineno = additionalInfo.lineno;
  }
  if (additionalInfo?.colno !== undefined) {
    details.colno = additionalInfo.colno;
  }

  if (error instanceof Error) {
    details.message = error.message;
    if (error.stack !== undefined) {
      details.stack = error.stack;
    }
  } else if (error instanceof ErrorEvent) {
    details.message = error.message;
    const filename = error.filename ?? additionalInfo?.filename;
    if (filename !== undefined) {
      details.filename = filename;
    }
    const lineno = error.lineno ?? additionalInfo?.lineno;
    if (lineno !== undefined) {
      details.lineno = lineno;
    }
    const colno = error.colno ?? additionalInfo?.colno;
    if (colno !== undefined) {
      details.colno = colno;
    }
    const stack = error.error instanceof Error ? error.error.stack : undefined;
    if (stack !== undefined) {
      details.stack = stack;
    }
  } else if (error instanceof PromiseRejectionEvent) {
    details.message = String(error.reason);
    const stack = error.reason instanceof Error ? error.reason.stack : undefined;
    if (stack !== undefined) {
      details.stack = stack;
    }
  } else {
    details.message = String(error);
  }

  return details;
}
